dist: bionic
language: generic
before_install:
- |
  echo "Checking if a CI run is needed post commit: ${TRAVIS_COMMIT_RANGE}"
  if ! git diff --name-only ${TRAVIS_COMMIT_RANGE} | grep -qvE '(\.png$)|(\.pdf$)|(\.html$)|^(LICENSE)'
  then
    echo "Only doc files were updated, not running the CI."
    exit
  fi
- sudo add-apt-repository --yes ppa:js-reynaud/kicad-5.1
- sudo apt update -y
- sudo apt install --no-install-recommends -y kicad kicad-symbols kicad-templates
  kicad-footprints inkscape
script:
- cd scripts && ./pcb2svg.sh && cd ..
before_deploy:
- git config --local user.name "PCB Gerber Exporter"
- git config --local user.email "noreply@w4xzr.xyz"
- export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
- git tag $TRAVIS_TAG
- ls
- ls Gerbers/
deploy:
  provider: releases
  api_key:
    secure: owWBxlTCdv0GC2wxnK3xCrA/BBqjBPOmbzxWQ42ZnA8sJlwybkhl5q8sJrl1XIaiwbiw8mivDDXW6HKkrAncntnXhQStkeA/oOKc+S8abqZ03MxiEdsWaCMwQaVY0WGu27iHOh6836kpDGG3ZA3ONARiY0/C0pvlqF987o4Fz7TnweqHDufMCDvUQfg0Ty/yOu2E2vj86hPeEkaMP+TBEzhpAGZnueMAIqir39DtYw3+VFwu1IWAK8p8KSBfa0ZKOjIzfxj61SYvTckUpk4/sFwrPNdhEomr6VGdOQ0Rwp8+OWtNjLZ4EVCIluS+ww9JduRbJfMu2EvYSVBFbWMaFwUqSqGVoFEspF1n0bcA0EldxqbI/gdgPZM8eCRgZrv0ekFuKb4gPvhdwEqOZWsA+mvw4XvzHV9MqSUUK4thVz3vW938H6biO7h2VMlinHrFbgJ5Txvz8GiCvgNe/4M/LlNW+UbWI8sX9LrmyH/7BZ3znbt/kPkb6ToC+JB5khlskAo1/FnvkNGO2OpCzA6Vo0Wy5iVlA1zJrodLZhuR+aRTBT1uoY3NQ4khewxAoBmSd64xIomWZUg3bhiBRtLBVTFfLheE3xNcuJt0CQtSwfte5EVCkEXcH2+f6CoRSA9kegeKAPHStPWg6NgV17RN/FE2rretqoHp3zAekw3Suok=
  file: Gerbers/PIN-117_gerbers.zip
  on:
    repo: w4xzr/PIN-117
  skip_cleanup: 'true'
